project:
  type: website

website:
  title: "LG전자 DX School"
  navbar:
    logo: "lglogo.png"
    background: "black"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

