project:
  type: website

website:
  title: <img src="lgedx_title.png" alt="LG EDX Title" class="title_img">

  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

