project:
  type: website

website:
  title: <img src="https://cdn.imweb.me/thumbnail/20240422/007568c9f6705.png" alt="LG EDX Title" class="title_img">

  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

